<a href="https://colab.research.google.com/github/tharakats/BankLoanEvaluator/blob/main/Model/BankLoanEvaluator.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
"""
Copyright 2020 Tharaka Sampath

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

In [3]:
import numpy as np
import pandas as pd

In [4]:
dataset = pd.read_csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vT3dBWyWxVw2rMsVnNaG36DWb33ecoq1Jd9i99ogk7S9mKDirDdg359NvLBmi5IlqLU9XFH4GLx6n_d/pub?gid=1809176138&single=true&output=csv')
X=dataset.iloc[:,3:-1].values
Y=dataset.iloc[:,-1].values

In [6]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
X[:,4:12]=imputer.fit_transform(X[:,4:12])

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=1)

In [29]:
X_train

array([[628, 1, 1, ..., 0.0, 1.0, 124749.08],
       [626, 0, 0, ..., 0.0, 0.0, 41104.82],
       [612, 1, 0, ..., 1.0, 1.0, 45750.21],
       ...,
       [672, 0, 0, ..., 1.0, 1.0, 92027.69],
       [663, 0, 0, ..., 1.0, 1.0, 101168.9],
       [763, 1, 1, ..., 1.0, 0.0, 33462.94]], dtype=object)

In [10]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder,StandardScaler
gender=LabelEncoder()
gender_x=gender.fit(X_train[:,2])

X_train[:,2]=gender_x.transform(X_train[:,2])
X_test[:,2]=gender_x.transform(X_test[:,2])

country=LabelEncoder()
country_x=country.fit(X_train[:,1])
X_train[:,1]=country_x.transform(X_train[:,1])
X_test[:,1]=country_x.transform(X_test[:,1])

In [30]:
X_train

array([[628, 1, 1, ..., 0.0, 1.0, 124749.08],
       [626, 0, 0, ..., 0.0, 0.0, 41104.82],
       [612, 1, 0, ..., 1.0, 1.0, 45750.21],
       ...,
       [672, 0, 0, ..., 1.0, 1.0, 92027.69],
       [663, 0, 0, ..., 1.0, 1.0, 101168.9],
       [763, 1, 1, ..., 1.0, 0.0, 33462.94]], dtype=object)

In [35]:
country_onehot=OneHotEncoder()
country_onehot_x=country_onehot.fit(X_train[:,1].reshape(-1,1))
country_onehot_x_train=country_onehot_x.transform(X_train[:,1].reshape(-1,1)).toarray()
country_onehot_x_test=country_onehot_x.transform(X_test[:,1].reshape(-1,1)).toarray()

X_train=np.concatenate((country_onehot_x_train,X_train),axis=1)
X_train=np.delete(X_train,4,axis=1)
X_test=np.concatenate((country_onehot_x_test,X_test),axis=1)
X_test=np.delete(X_test,4,axis=1)


In [36]:
X_train

array([[0.0, 1.0, 0.0, ..., 0.0, 1.0, 124749.08],
       [1.0, 0.0, 0.0, ..., 0.0, 0.0, 41104.82],
       [0.0, 1.0, 0.0, ..., 1.0, 1.0, 45750.21],
       ...,
       [1.0, 0.0, 0.0, ..., 1.0, 1.0, 92027.69],
       [1.0, 0.0, 0.0, ..., 1.0, 1.0, 101168.9],
       [0.0, 1.0, 0.0, ..., 1.0, 0.0, 33462.94]], dtype=object)

In [37]:
X_sc=StandardScaler()
X_sc=X_sc.fit(X_train)
X_train=X_sc.transform(X_train)
X_test=X_sc.transform(X_test)

In [38]:
import tensorflow as tf
import keras
from keras.models import Sequential
from keras.layers import Dense

classifier= keras.models.Sequential()
classifier.add(Dense(units=7,activation='relu',input_shape=(12,)))
classifier.add(Dense(units=7,activation='relu'))
classifier.add(Dense(units=1,activation='sigmoid'))

classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [39]:
classifier.fit(X_train,Y_train,batch_size=64,epochs=50,verbose=1)

Epoch 1/50
125/125 [==============================] - 0s 1ms/step - loss: 0.8130 - accuracy: 0.3573
Epoch 2/50
125/125 [==============================] - 0s 1ms/step - loss: 0.5908 - accuracy: 0.7140
Epoch 3/50
125/125 [==============================] - 0s 1ms/step - loss: 0.4996 - accuracy: 0.8085
Epoch 4/50
125/125 [==============================] - 0s 1ms/step - loss: 0.4586 - accuracy: 0.8166
Epoch 5/50
125/125 [==============================] - 0s 1ms/step - loss: 0.4346 - accuracy: 0.8235
Epoch 6/50
125/125 [==============================] - 0s 1ms/step - loss: 0.4161 - accuracy: 0.8324
Epoch 7/50
125/125 [==============================] - 0s 1ms/step - loss: 0.4003 - accuracy: 0.8388
Epoch 8/50
125/125 [==============================] - 0s 1ms/step - loss: 0.3875 - accuracy: 0.8431
Epoch 9/50
125/125 [==============================] - 0s 1ms/step - loss: 0.3775 - accuracy: 0.8457
Epoch 10/50
125/125 [==============================] - 0s 1ms/step - loss: 0.3703 - accuracy: 0.8476

In [40]:
classifier.evaluate(X_test,Y_test,batch_size=16)

125/125 [==============================] - 0s 769us/step - loss: 0.3336 - accuracy: 0.8635


[0.3335971534252167, 0.8634999990463257]